### ISSUE TITLE
Potential Issue with PPO Update Process in ppo_or.py

### ISSUE THREAD

**Issue by WaitDumplings** [cpwan/RLOR#2]
Hi,

I just read your new paper on Arxiv and followed your code. Thank you for sharing your work.

However, I noticed a potential issue in the implementation of PPO. Specifically, when I reviewed the process of updating PPO in **`ppo_or.py`**, I found something that seems inconsistent with the typical PPO algorithm.

In **`ppo_or.py`**, line 294, the following line calculates `cur_obs`:

```python
cur_obs = {k: v[mbenvinds] for k, v in obs[0].items()}
```

This appears to use the initial state for computing the current observations, which seems unusual. 
When we calculate the ratio:
ratio = pi(action_t | state_t) / pi(action_0 | state_0)

it appears that the ratio is based on the initial state (state_0) rather than the correct trajectory state at t. This deviates from the standard PPO algorithm, where the ratio should compare the probabilities of actions under the current and old policies at the same time step.

In contrast, the implementation in ppo.py seems to align more closely with the typical PPO format, where the ratio is computed as:

ratio = pi(action_t | state_t) / pi_old(action_t | state_t)

This follows the standard PPO update formula described in the literature.

Could you please clarify if this discrepancy is intentional? If so, it would be helpful to understand the reasoning behind this design choice.

Thank you for your time and for providing such an insightful paper and codebase!

**Comment by cpwan** [comment]
Hi there,
You can take a look between 294 and 302. The cur_obs is consumed to compute the encoder state and the encoder state is invariant across the steps. (In the model definition, all dynamic states are fed to the decoder but not the encoder.)

If this does not apply to your use case, you may need to change it accordingly.
